site_name: Wikipedia2Vec
repo_url: https://github.com/studio-ousia/wikipedia2vec
site_author: Studio Ousia
pages:
    - Home: index.md
    - Features: features.md
    - User Guide:
      - Installation: install.md
      - Learning Embeddings: commands.md
      - Basic Usage: usage.md
    - Pretrained Embeddings: pretrained.md
extra_css:
    - css/extra.css
theme:
    name: mkdocs
