site_name: Wikipedia2Vec
site_description: Wikipedia2Vec is a tool used for obtaining embeddings (vector representations) of words and entities from Wikipedia. The emnbeddings can be used as word embeddings, entity embeddings, and the unified embeddings of words and entities.
repo_url: https://github.com/wikipedia2vec/wikipedia2vec
edit_uri: ""
site_author: Studio Ousia
pages:
    - Home: index.md
    - Features: features.md
    - User Guide:
        - Installation: install.md
        - Learning Embeddings: commands.md
        - Basic Usage: usage.md
    - Pretrained Embeddings: pretrained.md
    - Benchmarks: benchmarks.md
extra_css:
    - css/extra.css
theme:
    name: mkdocs
    custom_dir: docs/custom_theme
markdown_extensions:
    - toc:
        permalink: 
